version: "3.8"
services:
  admin:
    build:
      context: ../
      dockerfile: docker/admin/Dockerfile
    ports:
      - 8088:8088

  user:
    build:
      context: ../
      dockerfile: docker/user/Dockerfile
    ports:
      - 8090:8090

  postgress:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: seulah
    ports:
      - 3233:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8082


